### ISSUE TITLE
New environment setup has issues in Windows

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-local#27]
Been getting a few remarks from Windows users that the environment configuration doesn't work.
They keep getting `waiting for network.................................`, also switching to a local or public IP doesn't seem to work.

cc @dalderupmaurice

**Comment by revett** [comment]
@jeroenptrs @DalderupMaurice - Can you please revert to the [84e0a73](https://github.com/CityOfZion/neo-local/tree/84e0a737d982f517fc8ca1658ba592358a67149b) commit and check if it the project works?

**Comment by shashank-ezdiagno** [comment]
Well it seems like I am also getting the same on mac - I could only figure out that neo scan container exits promptly with an error. I have got the container logs:

```
2018-07-15 06:03:27.172 [warn] [neoscan@127.0.0.1] found 0 missing blocks
2018-07-15 06:03:27.177 [error] [neoscan@127.0.0.1] GenServer NeoscanSync.TokenSyncer terminating
** (MatchError) no match of right hand side value: {:ok, []}
    (neoscan_node) lib/neoscan_node/notifications.ex:49: NeoscanNode.Notifications.get_token_notifications/0
    (neoscan_sync) lib/neoscan_sync/token_syncer.ex:30: NeoscanSync.TokenSyncer.sync_tokens/0
    (neoscan_sync) lib/neoscan_sync/token_syncer.ex:25: NeoscanSync.TokenSyncer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :sync

=CRASH REPORT==== 15-Jul-2018::06:03:27 ===
  crasher:
    initial call: Elixir.NeoscanSync.TokenSyncer:init/1
    pid: <0.1983.0>
    registered_name: 'Elixir.NeoscanSync.TokenSyncer'
    exception error: no match of right hand side value {ok,[]}
      in function  'Elixir.NeoscanNode.Notifications':get_token_notifications/0 (lib/neoscan_node/notifications.ex, line 49)
      in call from 'Elixir.NeoscanSync.TokenSyncer':sync_tokens/0 (lib/neoscan_sync/token_syncer.ex, line 30)
      in call from 'Elixir.NeoscanSync.TokenSyncer':handle_info/2 (lib/neoscan_sync/token_syncer.ex, line 25)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
    ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1849.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1707.0>,<0.1850.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 5164
  neighbours:

=SUPERVISOR REPORT==== 15-Jul-2018::06:03:27 ===
     Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
     Context:    child_terminated
     Reason:     {{badmatch,{ok,[]}},
                  [{'Elixir.NeoscanNode.Notifications',
                       get_token_notifications,0,
                       [{file,"lib/neoscan_node/notifications.ex"},{line,49}]},
                   {'Elixir.NeoscanSync.TokenSyncer',sync_tokens,0,
                       [{file,"lib/neoscan_sync/token_syncer.ex"},{line,30}]},
                   {'Elixir.NeoscanSync.TokenSyncer',handle_info,2,
                       [{file,"lib/neoscan_sync/token_syncer.ex"},{line,25}]},
                   {gen_server,try_dispatch,4,
                       [{file,"gen_server.erl"},{line,616}]},
                   {gen_server,handle_msg,6,
                       [{file,"gen_server.erl"},{line,686}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.1983.0>},
                  {id,'Elixir.NeoscanSync.TokenSyncer'},
                  {mfargs,{'Elixir.NeoscanSync.TokenSyncer',start_link,[]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]
```
happens several times and then process exits.

**Comment by jeroenptrs** [comment]
This specific issue seems to have been resolved with pulls #32 and #33

@DalderupMaurice still had an issue with the `neo-privatenet` docker image not wanting to pull.

**Comment by revett** [comment]
@shashank-ezdiagno Can you confirm that this is no longer an issue on your machine?

**Comment by revett** [comment]
@dalderupmaurice Are you having issues?

**Comment by DalderupMaurice** [comment]
😄 
![](https://i.imgur.com/TYeXNfb.png)

**Comment by jeroenptrs** [comment]
Seems like all issues have been resolved then!
